spring:
  application:
    name: service-registry

server:
  port: ${PORT:8080}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}