spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL}" #optional means, if config server is not available, still application will start

server:
  port: ${PORT:8080}