eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

management:
  tracing:
    sampling:
      probability: 1.0 # for 100% full logs visibility