name: Build & Push Microservices to Docker Hub

on:
  push:
    branches: [ "render_codeCleanUp" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [service-registry, department-service, config-server, employee-service, api-gateway]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR
        run: mvn -pl ${{ matrix.service }} -am clean package -DskipTests

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest ./${{ matrix.service }}

      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest

  deploy-to-render:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # =============================
      # 1. Deploy Config Server
      # =============================
      - name: Deploy Config Server
        run: |
          CONFIG_RESPONSE=$(curl -s -X POST "${{ secrets.CONFIG_HOOK }}")
          echo "$CONFIG_RESPONSE"
          CONFIG_DEPLOY_ID=$(echo $CONFIG_RESPONSE | jq -r '.id')
          echo "Config Deploy ID: $CONFIG_DEPLOY_ID"
          
          for i in {1..30}; do
            CONFIG_STATUS=$(curl -s \
              -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
              "https://api.render.com/v1/services/${{ secrets.CONFIG_SERVICE_ID }}/deploys/${CONFIG_DEPLOY_ID}" \
              | jq -r '.status')

            echo "[config-service] Status: $CONFIG_STATUS"

            if [ "$CONFIG_STATUS" = "live" ]; then
              echo "Config service deployed"
              break
            fi

            if [ "$CONFIG_STATUS" = "build_failed" ] || [ "$CONFIG_STATUS" = "update_failed" ]; then
              echo "Config service failed"
              exit 1
            fi

            echo "Waiting Config Server..."
            sleep 20
          done
          exit 1

      # =============================
      # 2. Deploy Service registry (Eureka)
      # =============================
      - name: Deploy Service registry (Eureka) Server
        run: |
          SERVICE_RESPONSE=$(curl -s -X POST "${{ secrets.SERVICE_HOOK }}")
          echo "$SERVICE_RESPONSE"
          SERVICE_DEPLOY_ID=$(echo $SERVICE_RESPONSE | jq -r '.id')
          echo "Service Deploy ID: $SERVICE_DEPLOY_ID"
          
          for i in {1..30}; do
            SERVICE_STATUS=$(curl -s \
              -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
              "https://api.render.com/v1/services/${{ secrets.SERVICE_SERVICE_ID }}/deploys/${SERVICE_DEPLOY_ID}" \
              | jq -r '.status')
          
            echo "[service-service] Status: $SERVICE_STATUS"
          
            if [ "$SERVICE_STATUS" = "live" ]; then
              echo "Service service deployed"
              break
            fi
          
            if [ "$SERVICE_STATUS" = "build_failed" ] || [ "$SERVICE_STATUS" = "update_failed" ]; then
              echo "Service service failed"
              exit 1
            fi
            echo "Waiting Service registry (Eureka) Server..."
            sleep 20
          done
          exit 1

      # =============================
      # 3. Deploy Department Service
      # =============================
      - name: Deploy Department Service
        run: |
          DEPARTMENT_RESPONSE=$(curl -s -X POST "${{ secrets.DEPARTMENT_HOOK }}")
          echo "$DEPARTMENT_RESPONSE"
          DEPARTMENT_DEPLOY_ID=$(echo $DEPARTMENT_RESPONSE | jq -r '.id')
          echo "Department Deploy ID: $DEPARTMENT_DEPLOY_ID"
          
          for i in {1..30}; do
            DEPARTMENT_STATUS=$(curl -s \
              -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
              "https://api.render.com/v1/services/${{ secrets.DEPARTMENT_SERVICE_ID }}/deploys/${DEPARTMENT_DEPLOY_ID}" \
              | jq -r '.status')
          
            echo "[department-service] Status: $DEPARTMENT_STATUS"
          
            if [ "$DEPARTMENT_STATUS" = "live" ]; then
              echo "Department service deployed"
              break
            fi
          
            if [ "$DEPARTMENT_STATUS" = "build_failed" ] || [ "$DEPARTMENT_STATUS" = "update_failed" ]; then
              echo "Department service failed"
              exit 1
            fi
            echo "Waiting Department Service..."
            sleep 20
          done
          exit 1

      # =============================
      # 4. Deploy Employee Service
      # =============================
      - name: Deploy Employee Service

        run: |
          EMPLOYEE_RESPONSE=$(curl -s -X POST "${{ secrets.EMPLOYEE_HOOK }}")
          echo "$EMPLOYEE_RESPONSE"
          EMPLOYEE_DEPLOY_ID=$(echo $EMPLOYEE_RESPONSE | jq -r '.id')
          echo "Employee Deploy ID: $EMPLOYEE_DEPLOY_ID"
          
          for i in {1..30}; do
            EMPLOYEE_STATUS=$(curl -s \
              -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
              "https://api.render.com/v1/services/${{ secrets.EMPLOYEE_SERVICE_ID }}/deploys/${EMPLOYEE_DEPLOY_ID}" \
              | jq -r '.status')
          
            echo "[employee-service] Status: $EMPLOYEE_STATUS"
          
            if [ "$EMPLOYEE_STATUS" = "live" ]; then
              echo "Employee service deployed"
              break
            fi
          
            if [ "$EMPLOYEE_STATUS" = "build_failed" ] || [ "$EMPLOYEE_STATUS" = "update_failed" ]; then
              echo "Employee service failed"
              exit 1
            fi
            echo "Waiting Employee Service..."
            sleep 20
          done
          exit 1


      # =============================
      # 5. Deploy API Gateway
      # =============================
      - name: Deploy Gateway

        run: |
          GATEWAY_RESPONSE=$(curl -s -X POST "${{ secrets.GATEWAY_HOOK }}")
          echo "$GATEWAY_RESPONSE"
          GATEWAY_DEPLOY_ID=$(echo $GATEWAY_RESPONSE | jq -r '.id')
          echo "Gateway Deploy ID: $GATEWAY_DEPLOY_ID"
          
          for i in {1..30}; do
            GATEWAY_STATUS=$(curl -s \
              -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
              "https://api.render.com/v1/services/${{ secrets.GATEWAY_SERVICE_ID }}/deploys/${GATEWAY_DEPLOY_ID}" \
              | jq -r '.status')
          
            echo "[gateway-service] Status: $GATEWAY_STATUS"
          
            if [ "$GATEWAY_STATUS" = "live" ]; then
              echo "Gateway service deployed"
              break
            fi
          
            if [ "$GATEWAY_STATUS" = "build_failed" ] || [ "$GATEWAY_STATUS" = "update_failed" ]; then
              echo "Gateway service failed"
              exit 1
            fi
            echo "Waiting Gateway Service..."
            sleep 20
          done
          exit 1


      # =============================
      # 7. Final validation
      # =============================
      - name: Final system check
        run: |
          echo "Checking full system health..."

          curl -f ${{ secrets.CONFIG_URL }} || exit 1
          curl -f ${{ secrets.SERVICE_URL }} || exit 1
          curl -f ${{ secrets.DEPARTMENT_URL }} || exit 1
          curl -f ${{ secrets.EMPLOYEE_URL }} || exit 1
          curl -f ${{ secrets.GATEWAY_URL }} || exit 1

          echo -e "\n\n::notice:: ALL SERVICES ARE UP AND HEALTHY"