name: Build & Push Microservices to Docker Hub

on:
  push:
    branches: [ "render_codeCleanUp" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [service-registry, department-service, config-server, employee-service, api-gateway]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR
        run: mvn -pl ${{ matrix.service }} -am clean package -DskipTests

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest ./${{ matrix.service }}

      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest

  trigger-deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deploy-simple workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "Simple Workflow"
          ref: render_codeCleanUp