name: Cleanup Docker Hub Tags

on:
  workflow_dispatch:
  schedule:
    - cron: '55 14 * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Delete old docker images on hub
        uses: snok/container-retention-policy@v3.0.1
        with:
          account: ${{ secrets.DOCKER_USERNAME }}
          token: ${{ secrets.DOCKER_TOKEN }}
          image-names: "*"
          cut-off: 1d
          keep-at-least: 1
          tag-selection: untagged