name: Simple Workflow

on:
  workflow_run:
    workflows: ["Build & Push Microservices to Docker Hub"]  # must match name in workflow build-docker.yml
    types:
      - completed

jobs:
  simple-job:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a simple command
        run: echo "Hello from GitHub Actions"