name: Second Action

on:
  workflow_run:
    workflows: ["Build & Push Microservices to Docker Hub"]
    types: [completed]
    branches: [ "render_codeCleanUp" ]

jobs:
  run-second-action:
    if: github.event.workflow_run.conclusion == 'success'  # Only run if first workflow succeeded
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Run second action
        run: echo "Second action running after first workflow completes successfully"